### ISSUE TITLE
verisim make error: source file './FIRRTLBaseVisitor.java' could not be found

### ISSUE THREAD

**Issue by shirlynan** [riscv-boom/boom-template#36]
make -C /home/test/boom-template/rocket-chip/firrtl SBT="java -Xmx8G -Xss8M -jar /home/test/boom-template/rocket-chip/sbt-launch.jar ++2.12.4" root_dir=/home/test/boom-template/rocket-chip/firrtl build-scala
make[1]: Entering directory '/home/test/boom-template/rocket-chip/firrtl'
java -Xmx8G -Xss8M -jar /home/test/boom-template/rocket-chip/sbt-launch.jar ++2.12.4 "assembly"
[info] Loading settings for project firrtl-build from plugins.sbt ...
[info] Loading project definition from /home/test/boom-template/rocket-chip/firrtl/project
[info] Updating ProjectRef(uri("file:/home/test/boom-template/rocket-chip/firrtl/project/"), "firrtl-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project firrtl from build.sbt ...
[info] Set current project to firrtl (in build file:/home/test/boom-template/rocket-chip/firrtl/)
[info] Setting Scala version to 2.12.4 on 1 projects.
[info] Reapplying settings...
[info] Set current project to firrtl (in build file:/home/test/boom-template/rocket-chip/firrtl/)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 protobuf files to /home/test/boom-template/rocket-chip/firrtl/target/scala-2.12/src_managed/main
[info] Compiling schema /home/test/boom-template/rocket-chip/firrtl/src/main/proto/firrtl.proto
protoc-jar: protoc version: 3.5.1, detected platform: linux-x86_64 (linux/amd64)
protoc-jar: embedded: bin/3.5.1/protoc-3.5.1-linux-x86_64.exe
protoc-jar: executing: [/tmp/protocjar17305608848001377076/bin/protoc.exe, -I/home/test/boom-template/rocket-chip/firrtl/src/main/proto, -I/home/test/boom-template/rocket-chip/firrtl/target/protobuf_external, --java_out=/home/test/boom-template/rocket-chip/firrtl/target/scala-2.12/src_managed/main, /home/test/boom-template/rocket-chip/firrtl/src/main/proto/firrtl.proto]
[info] Compiling protobuf
[info] Protoc target directory: /home/test/boom-template/rocket-chip/firrtl/target/scala-2.12/src_managed/main
[info] Compiling 119 Scala sources and 5 Java sources to /home/test/boom-template/rocket-chip/firrtl/target/scala-2.12/classes ...
[error] source file '/home/test/boom-template/rocket-chip/firrtl/target/scala-2.12/src_managed/main/firrtl/antlr/FIRRTLBaseVisitor.java' could not be found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed Jun 17, 2019, 10:46:02 AM

**Comment by abdullahyildiz** [comment]
I get the same error. How did you fix that?

**Comment by jerryz123** [comment]
`boom-template` is deprecated. This repository will not work with newer versions of BOOM, and we will not continue pushing bug fixes into this repository. 

To use BOOM, please look at the Chipyard SoC design framework: https://github.com/ucb-bar/chipyard

Functionality should be similar to boom-template
